import { useEffect, useState } from 'react'
import { api, type CreateRunParams } from './api'
import type { MetricsSummary, Incident } from './types'
import { Sidebar } from './components/Sidebar'
import { IncidentBanner } from './components/IncidentBanner'
import { LiveCounter } from './components/LiveCounter'
import { CaseDrilldown } from './components/CaseDrilldown'
import { BanditChart } from './components/BanditChart'
import { PortfolioComparison } from './components/PortfolioComparison'
import { PromiseTracker } from './components/PromiseTracker'
import { ApprovalQueue } from './components/ApprovalQueue'

const DEFAULT_PARAMS: CreateRunParams = {
  n: 500,
  seed: 1,
  policy_mode: 'deterministic',
  inject_spike: true,
  use_llm: false,
  auto_approve: true,
}

export default function App() {
  const [params, setParams] = useState<CreateRunParams>(DEFAULT_PARAMS)
  const [capacityHours, setCapacityHours] = useState(20)
  const [runId, setRunId] = useState<string | null>(null)
  const [summary, setSummary] = useState<MetricsSummary | null>(null)
  const [incidents, setIncidents] = useState<Incident[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const generateRun = async (p: CreateRunParams) => {
    setLoading(true)
    setError(null)
    try {
      const resp = await api.createRun(p)
      setRunId(resp.run_id)
      setSummary(resp.summary)
      setIncidents(resp.incidents)
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    generateRun(DEFAULT_PARAMS)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <div className="app-shell">
      <Sidebar
        params={params}
        setParams={setParams}
        capacityHours={capacityHours}
        setCapacityHours={setCapacityHours}
        onGenerate={() => generateRun(params)}
        loading={loading}
      />
      <div className="main">
        <header style={{ marginBottom: 24 }}>
          <h1 style={{ fontSize: 26 }}>💸 AI Revenue Recovery Agent</h1>
          <p style={{ color: 'var(--text-muted)', marginTop: 6, fontSize: 13.5 }}>
            Detects revenue at risk across failed subscriptions, abandoned checkouts, and overdue B2B
            receivables — diagnoses why, decides if it's worth pursuing, picks the best recovery action,
            respects compliance stopping rules, and logs every decision in a tamper-evident audit trail.
          </p>
        </header>

        {error && <div className="banner banner-danger">⚠️ {error}</div>}

        {!runId || !summary ? (
          <p className="loading-text">Generating batch and running the agent…</p>
        ) : (
          <>
            <section className="section">
              {incidents.length > 0 ? (
                incidents.map((inc, i) => <IncidentBanner key={i} incident={inc} />)
              ) : (
                <div className="banner banner-success">✅ No systemic incidents detected in the current batch.</div>
              )}
            </section>

            <section className="section">
              <LiveCounter runId={runId} summary={summary} />
            </section>

            <section className="section">
              <ApprovalQueue runId={runId} />
            </section>

            <section className="section">
              <CaseDrilldown runId={runId} />
            </section>

            <section className="section">
              <BanditChart />
            </section>

            <section className="section">
              <PortfolioComparison runId={runId} capacityHours={capacityHours} />
            </section>

            <section className="section">
              <PromiseTracker runId={runId} />
            </section>

            <div className="footer-note">
              <strong>Data note:</strong> all events, outcomes, and recovered amounts on this page are
              generated by <code>data/generate_synthetic.py</code> and scored by{' '}
              <code>core/outcome_simulator.py</code>'s effectiveness matrix — a controlled simulation, not
              a live payments feed. Run <code>{runId}</code> · see README.md's "What's simulated vs real"
              section for the full breakdown.
            </div>
          </>
        )}
      </div>
    </div>
  )
}
